In [308]:
from sklearn import datasets
import numpy as np
import pandas as pd

In [309]:
iris= datasets.load_iris()

In [310]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

### Ejercicio 1

In [311]:
d= iris.data

In [312]:
t= iris.target

In [313]:
t.shape

(150,)

In [314]:
d[np.arange(10)]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [315]:
t[np.arange(10)]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Ejercicio 2

In [316]:
t2=t.reshape (150,-1)

In [317]:
m = np.concatenate((d,t2), axis=1)

In [318]:
m2=m[np.arange(5)]
m2

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ]])

### Ejercicio 3

In [319]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [320]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [321]:
media_sepal=np.mean(m2[:,0])
desv_estandar_sepal=np.std(m2[:,0])
print(f"la media de la longitud del sepalo es: {media_sepal:.2f}")
print(f"la desviacion estandar de la longitud del sepalo es: {desv_estandar:.2f}")

la media de la longitud del sepalo es: 4.86
la desviacion estandar de la longitud del sepalo es: 0.19


In [322]:
media_petal=np.mean(m2[:,2])
dev_estandar_petal=np.std(m2[:,2])
print(f"la media de la longitud del petalo es: {media_petal:.2f}")
print(f"la desviacion estandar de la longitud del petalo es: {dev_estandar_petal:.2f}")

la media de la longitud del petalo es: 1.40
la desviacion estandar de la longitud del petalo es: 0.06


 ### Ejercicio 4


In [323]:
m_random= m[np.random.choice(m.shape[0], 20, replace=False)]
m_random

array([[6.5, 3. , 5.5, 1.8, 2. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.5, 2.3, 1.3, 0.3, 0. ],
       [5.7, 2.8, 4.5, 1.3, 1. ],
       [6.7, 3.1, 5.6, 2.4, 2. ],
       [7.7, 2.8, 6.7, 2. , 2. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [6.8, 3. , 5.5, 2.1, 2. ],
       [5.5, 2.3, 4. , 1.3, 1. ],
       [6.2, 2.2, 4.5, 1.5, 1. ],
       [6.3, 2.3, 4.4, 1.3, 1. ],
       [5.7, 2.9, 4.2, 1.3, 1. ],
       [6. , 2.2, 5. , 1.5, 2. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [4.7, 3.2, 1.6, 0.2, 0. ],
       [7.4, 2.8, 6.1, 1.9, 2. ],
       [6.3, 2.8, 5.1, 1.5, 2. ],
       [6.7, 3.3, 5.7, 2.5, 2. ],
       [5.6, 3. , 4.1, 1.3, 1. ]])

 ### Ejercicio 5


In [324]:
mean_total=[]
for i in range(3):
    mean=np.mean(m[m[:, 4] == i,:4], axis=0)
    mean_total.append(mean)
    std=np.std(m[m[:,4] == i,:4], axis=0)
    print(mean)
    print(std)

[5.006 3.428 1.462 0.246]
[0.34894699 0.37525458 0.17191859 0.10432641]
[5.936 2.77  4.26  1.326]
[0.51098337 0.31064449 0.46518813 0.19576517]
[6.588 2.974 5.552 2.026]
[0.62948868 0.31925538 0.54634787 0.27188968]


In [325]:
mean_total

[array([5.006, 3.428, 1.462, 0.246]),
 array([5.936, 2.77 , 4.26 , 1.326]),
 array([6.588, 2.974, 5.552, 2.026])]

 ### Ejercicio 6

In [326]:
iris.target_names[0]

'setosa'

In [327]:
for i in range(3):
    print("La cantidad de muestras de", iris.target_names[i], "es :" ,len(m[m[:,4] == i,4]))

La cantidad de muestras de setosa es : 50
La cantidad de muestras de versicolor es : 50
La cantidad de muestras de virginica es : 50


In [328]:
mean_tot_m=np.array(mean_total)
mean_tot_m

array([[5.006, 3.428, 1.462, 0.246],
       [5.936, 2.77 , 4.26 , 1.326],
       [6.588, 2.974, 5.552, 2.026]])

In [329]:
print("La especie con el valor maximo promedio es :", iris.target_names[np.argmax(mean_tot_m[:, 0])])

La especie con el valor maximo promedio es : virginica


 ### Ejercicio 7

In [330]:
np.corrcoef(d, rowvar=False)

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])

In [331]:
media_petal

1.4

In [332]:
m[m[:,2] > media_petal]

array([[4.6, 3.1, 1.5, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [4.7, 3.2, 1.6, 0.2, 0. ],
       [4.8, 3.1, 1.6, 0.2, 0. ],
       [5.4, 3.4, 1.5, 0.4, 0. ],
       [5.2, 4.1, 1.5, 0.1, 0. ],
       [4.9, 3.1, 1.5, 0.2, 0. ],
       [5.1, 3.4, 1.5, 0.2, 0. ],
       [5. , 3.5, 1.6, 0.6, 0. ],
       [5.1, 3.8, 1.9, 0.4, 0. ],
       [5.1, 3.8, 1.6, 0.2, 0. ],
       [5.3, 3.7, 1.5, 0.2, 0. ],
       [7. , 3.2, 4.7, 1.4, 1. ],
       [6.4, 3.2, 4.5, 1.5, 1. ],
       [6.9, 3.1, 4.9, 1.5, 1. ],
       [5.5, 2

In [333]:
print("La muestras con petalos mas grandes es :", (max(d[:, 2])), "de la especie", iris.target_names[i] )

La muestras con petalos mas grandes es : 6.9 de la especie virginica


 ### Ejercicio 8

In [334]:
mean_tot_m

array([[5.006, 3.428, 1.462, 0.246],
       [5.936, 2.77 , 4.26 , 1.326],
       [6.588, 2.974, 5.552, 2.026]])

In [335]:
dif=np.diff(mean_tot_m[:, [0,2]], axis=1)
dif

array([[-3.544],
       [-1.676],
       [-1.036]])

In [336]:
print("La especie con mayor diferencia entre,longitud media de sépalos y pétalos es :", iris.target_names[np.argmax(dif)])

La especie con mayor diferencia entre,longitud media de sépalos y pétalos es : virginica
