In [3]:
from sklearn import datasets
import numpy as np
import pandas as pd

In [4]:
iris= datasets.load_iris()

In [5]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

### Ejercicio 1
Cargar "fecha" y "target" del conjunto de datos, y visualiza los 10 primeros registros de cada uno.

In [6]:
d= iris.data

In [7]:
t= iris.target

In [8]:
t.shape

(150,)

In [10]:
d[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [14]:
t[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Ejercicio 2
Concatena "fecha" y "target" en un nuevo array. Muestra los 5 primeros registros.

In [29]:
t.reshape (150,-1)

In [16]:
m = np.concatenate((d,t), axis=1)

In [36]:
m[:5]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ]])

### Ejercicio 3
Calcula la media y desviación estándar de la longitud del sépalo ("sepal length (cm)") y la longitud del pétalo ("petal length (cm)"). Muestra los resultados con dos decimales.

In [38]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [42]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [43]:
media_sepal=np.mean(m[:,0])
desv_estandar_sepal=np.std(m[:,0])
print(f"la media de la longitud del sepalo es: {media_sepal:.2f}")
print(f"la desviacion estandar de la longitud del sepalo es: {desv_estandar_sepal:.2f}")

la media de la longitud del sepalo es: 5.84
la desviacion estandar de la longitud del sepalo es: 0.83


In [44]:
media_petal=np.mean(m[:,2])
dev_estandar_petal=np.std(m[:,2])
print(f"la media de la longitud del petalo es: {media_petal:.2f}")
print(f"la desviacion estandar de la longitud del petalo es: {dev_estandar_petal:.2f}")

la media de la longitud del petalo es: 3.76
la desviacion estandar de la longitud del petalo es: 1.76


 ### Ejercicio 4
Selecciona una muestra aleatoria de 20 registros del conjunto obtenidos en el ejercicio anterior.



In [69]:
mr= m[np.random.choice(m.shape[0], 20, replace=False)]
mr

array([[5.8, 2.8, 5.1, 2.4, 2. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.1, 3.8, 1.9, 0.4, 0. ],
       [7. , 3.2, 4.7, 1.4, 1. ],
       [6. , 2.2, 5. , 1.5, 2. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [5.3, 3.7, 1.5, 0.2, 0. ],
       [5.2, 4.1, 1.5, 0.1, 0. ],
       [6.4, 2.8, 5.6, 2.1, 2. ],
       [5.6, 2.5, 3.9, 1.1, 1. ],
       [6.8, 2.8, 4.8, 1.4, 1. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [5.1, 3.4, 1.5, 0.2, 0. ],
       [5.8, 2.7, 5.1, 1.9, 2. ],
       [6.9, 3.2, 5.7, 2.3, 2. ],
       [7.1, 3. , 5.9, 2.1, 2. ],
       [6.9, 3.1, 4.9, 1.5, 1. ],
       [5.8, 2.7, 4.1, 1. , 1. ],
       [4.9, 3.1, 1.5, 0.2, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ]])

 ### Ejercicio 5
Crea una matriz que muestre: 

• La media de cada característica por especie. 

• La desviación estándar de cada característica por especie.

In [70]:
mean_total=[]
for i in range(3):
    mean=np.mean(mr[mr[:, 4] == i,:4], axis=0)
    mean_total.append(mean)
    std=np.std(mr[mr[:,4] == i,:4], axis=0)
    print(mean)
    print(std)

[5.13333333 3.54444444 1.48888889 0.21111111]
[0.27888668 0.40582183 0.17284832 0.08748898]
[6.42 2.86 4.48 1.28]
[0.59464275 0.25768197 0.40199502 0.19390719]
[6.33333333 2.78333333 5.4        2.05      ]
[0.51532083 0.30776976 0.34641016 0.29297326]


los anteriores datos se organizan, fila de medias y fila de desviacion estandar por cada especie, siendo las filas 0 ( media) 
y 1 desviacion estandar para la especie 0 (setona), 2 (media) y 3 (desviacion estandar) para especie 1 ( versicolor); filas 4 
(media) y 5 (desviacion estandar) para especia 2 ( virignica)

In [73]:
mean_total

[array([5.13333333, 3.54444444, 1.48888889, 0.21111111]),
 array([6.42, 2.86, 4.48, 1.28]),
 array([6.33333333, 2.78333333, 5.4       , 2.05      ])]

la matriz mean_total, unifica los valores de medias de cada especie por columnas (features_names), siendo la fila 0 
(0 = setona ), fila 1 ( 1= versicolor), fila 2 (2=virginica)

 ### Ejercicio 6
  Calcula la cantidad de muestras por especie.

• Encuentra la especie con el valor máximo promedio de la variable "sepal length (cm)"

In [74]:
iris.target_names[0]

'setosa'

In [75]:
for i in range(3):
    print("La cantidad de muestras de", iris.target_names[i], "es :" ,len(mr[mr[:,4] == i,4]))

La cantidad de muestras de setosa es : 9
La cantidad de muestras de versicolor es : 5
La cantidad de muestras de virginica es : 6


In [76]:
mean_tot_m=np.array(mean_total)
mean_tot_m

array([[5.13333333, 3.54444444, 1.48888889, 0.21111111],
       [6.42      , 2.86      , 4.48      , 1.28      ],
       [6.33333333, 2.78333333, 5.4       , 2.05      ]])

Convierto la matriz meanto_total a matriz Numpy con dos dimenciones para poder trabajar sobre ella. igualmente cada fila 0,1,2 corresponde a la especie en su mismo orden

In [147]:
print("La especie con el valor maximo promedio es :", iris.target_names[np.argmax(mean_tot_m[:, 0])])

La especie con el valor maximo promedio es : versicolor


 ### Ejercicio 7
• Calcula la matriz de correlación entre las variables.

• Filtra los valores mayores a la media de la longitud de los pétalos y muéstralo. 

• Encuentra la muestra con los pétalos más grandes.

In [127]:
np.corrcoef(mr, rowvar=False)

array([[ 1.        , -0.30760498,  0.84641487,  0.78195116,  0.70900903],
       [-0.30760498,  1.        , -0.65418424, -0.58510055, -0.67525938],
       [ 0.84641487, -0.65418424,  1.        ,  0.96754383,  0.95416657],
       [ 0.78195116, -0.58510055,  0.96754383,  1.        ,  0.96748607],
       [ 0.70900903, -0.67525938,  0.95416657,  0.96748607,  1.        ]])

In [128]:
media_petal

3.7580000000000005

In [203]:
mr[mr[:,2] > media_petal]

array([[5.8, 2.8, 5.1, 2.4, 2. ],
       [7. , 3.2, 4.7, 1.4, 1. ],
       [6. , 2.2, 5. , 1.5, 2. ],
       [6.4, 2.8, 5.6, 2.1, 2. ],
       [5.6, 2.5, 3.9, 1.1, 1. ],
       [6.8, 2.8, 4.8, 1.4, 1. ],
       [5.8, 2.7, 5.1, 1.9, 2. ],
       [6.9, 3.2, 5.7, 2.3, 2. ],
       [7.1, 3. , 5.9, 2.1, 2. ],
       [6.9, 3.1, 4.9, 1.5, 1. ],
       [5.8, 2.7, 4.1, 1. , 1. ]])

In [202]:
print("La muestras con petalos mas grandes es :", (max(mr[:, 2])), "de la especie", 
      iris.target_names[int(mr[np.argmax(mr[:, 2]),4])])

La muestras con petalos mas grandes es : 5.9 de la especie virginica


 ### Ejercicio 8
 Halla la especie con la mayor diferencia entre la longitud media de sépalos y pétalos.

In [132]:
mean_tot_m

array([[5.13333333, 3.54444444, 1.48888889, 0.21111111],
       [6.42      , 2.86      , 4.48      , 1.28      ],
       [6.33333333, 2.78333333, 5.4       , 2.05      ]])

In [188]:
dif=np.abs(np.diff(mean_tot_m[:, [0,2]], axis=1))
dif

array([[3.64444444],
       [1.94      ],
       [0.93333333]])

Para hallar la mayor diferencia, se necesito convertiro la matriz en en valorex absolutos. es importante guardar los valores en una variable para que puedan ser luego interpretados por python.

In [189]:
print("La especie con mayor diferencia entre,longitud media de sépalos y pétalos es :", iris.target_names[np.argmax(dif)])

La especie con mayor diferencia entre,longitud media de sépalos y pétalos es : setosa
